    with open(File_Path,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Ellumination\\Projects\\_elan_\\elan\\Scripts\\Frank\\000_NVR_Timeline_Check.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Eluminate/Projects/_elan_/elan/Scripts/Frank/000_NVR_Timeline_Check.py", line 442, in <module>
    ForceCloseViewer()
NameError: name 'ForceCloseViewer' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Eluminate/Projects/_elan_/elan/Scripts/Frank/000_NVR_Timeline_Check.py", line 467, in <module>
    ForceCloseViewer()
NameError: name 'ForceCloseViewer' is not defined
